image: node:latest

services:
  - name: mongo:latest

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  tags:
    - "main"
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  tags:
    - "main"
  script:
    - mongod --dbpath=src/app_server/mongodb/data --nojournal
    - npm test

heroku:
  stage: deploy
  tags:
    - "main"
  script: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git HEAD:master
