image: node:latest

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  tags:
    - "main"
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build_ts:
  stage: build
  tags:
    - "main"
  script:
    - npm run tsc

testing:
  stage: test
  tags:
    - "main"
  script: npm test

heroku:
  stage: deploy
  tags:
    - "main"
  script: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git master --force
